### PR TITLE
fixed fishing delay slider

### PR DESCRIPTION
**Pull request by max-the-mage**
Made a few changes to fix the delay slider when using fishing mode. It now properly updates the variable when needed so it is used by the delay when fishing. I also decreased the delay between the mouse down and mouse up, since it was previously long enough to trigger a hold, which can cause issues with AFK fishing on servers with high ping or low TPS.

Resolves Issue #7

### CODE REVIEW

**Comment by davidlaym** [comment]
@monpjc can you merge this please? i'm having issues with the defaul delay

**Comment by muazamkamal** [comment]
Seconded. Had to manually change the script to get the delay I needed for MP server. This pull should fix the delay slider.

**Review by Ragingfire105 — CHANGES_REQUESTED** [review]
You need a gLabel because it saves the sliders current value to it's variable.  This is so you can have logic based on the value of the slider.  Other controls you would need to put a 'gui submit nohide' in the gLabel to retrieve there values.  Submit nohide is basically the 'apply' command of a GUI in AHK.  

Also the gLabel can be shortened to just

SliderSet:
{Tab}return

Tab being a litteral tab.  Any one liner conditional commands can be written this way.

**Comment by monpjc** [comment]
Will be merged with other changes soon

**Review by monpjc — COMMENTED** [review]
Thank you for notes

**Pull request closed without merging**
