### PR TITLE
Added GUI Hide and show functions.

### PR DESCRIPTION
**Pull request by Ragingfire105**
Added the ability to hide the main GUI to simulate a minimize to system tray function.  The script already had a system tray icon.  This required naming the main and start GUI so that the Hide/Show functions can properly target it.  Also, converted Xisumavoid's face, sourced from HermitCraft Fandom wiki (https://hermitcraft.fandom.com/wiki/XisumaVoid), into an ICO file, located in me fork, for use by the script.  This is so the tray and taskbar icons are unique from other AHK scripts to curb confusion for users who already have other scripts running.

Side note:  The overall GUI code can be cleaned up ALOT by using the named GUI methods and giving the text controls vLabels for targeting.  This would allow for the GUI to be simply modified instead of being destroyed and rebuilt.  If you want me to do this I can.

### CODE REVIEW

**Comment by Ragingfire105** [comment]
Added alternate pull request with additional changes, #24 .
Additional changes are previously mentioned side note. 

P.S. Leaving this Pull Request open so either some, all or none of the changes can be merged. ;-)

**Comment by monpjc** [comment]
Hi, when I started this project X gave me some basic scripts and I had to learn AHK on the fly so yes there is a lot thats needed updating in this release.
Much of what you have stated in being rewritten for the next major release 1.0 so I will keep this open and merge some of your ideas.
Thanks :)

**Comment by Ragingfire105** [comment]
Looking forward to Version 1.0.  

I will keep an eye out for any more improvements I might come up with.  I am by no means an expert in AHK. Though, I have been using it sparingly in both my personal and professional life to bend things to my will for at least 12 years.

**Comment by histefanhere** [comment]
Hey Ragingfire,

I've recently taken the liberty of continuing this project. Your contributions really are awesome! The GUI code was a mess before I saw this fork, so I merged it into my fork which has now been merged into main (#24) , meaning all the contributions have already been merged, therefore I am closing this pull request.

A big UI re-work is in the books and your code will be center piece to all that, so I thank you very much! :)

**Pull request closed without merging**
